global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Spring Boot application metrics
  - job_name: 'healthrecord-app'
    static_configs:
      - targets: [ 'healthrecord-app:8080' ]
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # System metrics from Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
